spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: a9ikfAzGfdHBCOfYSKvy
            clientSecret: VQW9Ek2MQJ
            redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorizationGrantType: authorization_code
            scope:
              - name
              - email
            clientName: Naver
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response